name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  primitives-tests:
    name: Run Primitives Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B compile

      - name: Run Primitives Tests
        run: mvn -B test -Dtest=primitives.**.*Test
        env:
          MAVEN_OPTS: "-Dtest=primitives.**.*Test"

      - name: Publish Primitives Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "target/surefire-reports/TEST-primitives.*.xml"
          detailed_summary: true
          check_name: "Primitives Test Results"

  geometries-tests:
    name: Run Geometries Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B compile

      - name: Run Geometries Tests
        run: mvn -B test -Dtest=geometries.**.*Test
        env:
          MAVEN_OPTS: "-Dtest=geometries.**.*Test"

      - name: Publish Geometries Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "target/surefire-reports/TEST-geometries.*.xml"
          detailed_summary: true
          check_name: "Geometries Test Results"
