name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  primitives-tests:
    name: Run Primitives Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B compile

      - name: Run Primitives Tests
        run: mvn -B test -Dtest=primitives.**.*Test -DtrimStackTrace=false -Dsurefire.reportFormat=xml
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Publish Primitives Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "target/surefire-reports/TEST-*.xml"
          detailed_summary: true
          check_name: "Primitives Test Results"
          include_passed: true
          annotate_notice: false
          fail_on_failure: false
          require_tests: true
          job_summary: true

  geometries-tests:
    name: Run Geometries Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B compile

      - name: Run Geometries Tests
        run: mvn -B test -Dtest=geometries.**.*Test -DtrimStackTrace=false -Dsurefire.reportFormat=xml
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Publish Geometries Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "target/surefire-reports/TEST-*.xml"
          detailed_summary: true
          check_name: "Geometries Test Results"
          include_passed: true
          annotate_notice: false
          fail_on_failure: false
          require_tests: true
          job_summary: true
