name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B compile

      - name: Run tests with Maven
        run: mvn -B test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # Always run this step to publish test results even when there are test failures
        with:
          report_paths: "target/surefire-reports/TEST-*.xml"
          detailed_summary: true
          check_name: "JUnit Test Results"
